apiVersion: v1
appVersion: V.0.1
description: 'Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.'
name: chin
version: 0.1.0
home: chin.zzuid-drecht.nl
icon: chin.zuid-drecht.nl
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
      condition: postgresql.enabled
