apiVersion: v1
entries:
  chin:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-22T17:54:54.1677999Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 7be2fb03b00fcbf7322220fb7aed4af031c4c1ac600660f965847c08e25bf3f5
    home: chin.zzuid-drecht.nl
    icon: chin.zuid-drecht.nl
    name: chin
    urls:
    - chin-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-22T17:54:54.1627037Z"
