apiVersion: v1
entries:
  chin:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-09-29T09:36:30.224665139Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 66a95c3d55a384f22bc7a246ed248f8c60172c563c146cf43448ae6aeffebc24
    home: chin.zzuid-drecht.nl
    icon: chin.zuid-drecht.nl
    name: chin
    urls:
    - chin-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-29T09:36:30.220837138Z"
